pipeline:
  name: AI Orchestration Hub Pipeline
  identifier: ai_orchestration_hub_pipeline
  projectIdentifier: swarm_command_center
  orgIdentifier: hugefisco94
  tags:
    environment: production
    project: ai-orchestration-hub
  properties:
    ci:
      codebase:
        connectorRef: github_hugefisco94
        repoName: ai-orchestration-hub
        build: <+input>
  stages:
    - stage:
        name: Validate
        identifier: validate
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: JSON Validation
                  identifier: json_validation
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "=== JSON Data Validation ==="
                      for f in data/*.json; do
                        python3 -c "import json; json.load(open('$f'))" || exit 1
                        echo "✓ $f valid"
                      done
                      echo "All data files validated."
                    timeout: 5m
              - step:
                  name: JS Syntax Check
                  identifier: js_syntax_check
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "=== JavaScript Syntax Check ==="
                      node --check js/app.js && echo "✓ app.js"
                      node --check js/components.js && echo "✓ components.js"
                      node --check js/interactive.js && echo "✓ interactive.js"
                      node --check sw.js && echo "✓ sw.js"
                      node --check server.js && echo "✓ server.js"
                      echo "All JS files syntax OK."
                    timeout: 5m

    - stage:
        name: Quality Gate
        identifier: quality_gate
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: HTML Structure Check
                  identifier: html_check
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "=== HTML Structure Check ==="
                      grep -q '<!DOCTYPE html>' index.html && echo "✓ DOCTYPE"
                      grep -q 'lang=' index.html && echo "✓ lang attribute"
                      grep -q 'serviceWorker' index.html && echo "✓ SW registration"
                      grep -q 'interactive.js' index.html && echo "✓ interactive.js loaded"
                      echo "HTML structure OK."
                    timeout: 5m
              - step:
                  name: Service Worker Presence
                  identifier: sw_check
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "=== Service Worker Check ==="
                      test -f sw.js && echo "✓ sw.js exists"
                      grep -q '/api/health' sw.js && echo "✓ /api/health endpoint"
                      grep -q '/api/route' sw.js && echo "✓ /api/route endpoint"
                      grep -q '/api/models' sw.js && echo "✓ /api/models endpoint"
                      grep -q '/api/sentinel' sw.js && echo "✓ /api/sentinel endpoint"
                      grep -q '/api/activity' sw.js && echo "✓ /api/activity endpoint"
                      echo "SW backend complete."
                    timeout: 5m
              - step:
                  name: Bilingual Content Check
                  identifier: i18n_check
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "=== Bilingual Content Check ==="
                      KO_ONLY=$(grep -c 'data-ko-only' index.html)
                      echo "Korean-only elements: $KO_ONLY"
                      DATA_EN=$(grep -c 'data-en=' index.html)
                      echo "Bilingual elements: $DATA_EN"
                      test $KO_ONLY -ge 5 && echo "✓ Sufficient Korean elements"
                      echo "i18n check complete."
                    timeout: 5m

    - stage:
        name: Build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Install Dependencies
                  identifier: npm_install
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      npm ci --only=production 2>/dev/null || npm install --only=production
                      echo "✓ Dependencies installed"
                    timeout: 10m
              - step:
                  name: Server Smoke Test
                  identifier: server_test
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      node server.js &
                      SERVER_PID=$!
                      sleep 3
                      curl -sf http://localhost:3000/api/health | python3 -c "import json,sys; d=json.load(sys.stdin); assert d['status']=='ok'; print('✓ Health check passed')"
                      kill $SERVER_PID 2>/dev/null
                      echo "Server smoke test complete."
                    timeout: 5m

    - stage:
        name: Deploy
        identifier: deploy
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Deploy via Harness Engineering
                  identifier: deploy_harness
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "=== Harness Engineering Deploy ==="
                      echo "Strategy: Harness CI → GitHub Pages (Legacy Build)"
                      echo "Note: GitHub Actions disabled — using Harness-native deployment"
                      echo ""
                      echo "--- Step 1: Validate deployment artifacts ---"
                      test -f index.html && echo "✓ index.html"
                      test -f sw.js && echo "✓ sw.js (Service Worker backend)"
                      test -f server.js && echo "✓ server.js (Express backend)"
                      test -f .nojekyll && echo "✓ .nojekyll (Jekyll bypass)"
                      test -d .harness && echo "✓ .harness/ (pipeline config)"
                      echo ""
                      echo "--- Step 2: Push to deployment branch ---"
                      git config user.name "Harness CI"
                      git config user.email "harness@ci.hugefisco94.dev"
                      git checkout master 2>/dev/null || git checkout -b master
                      git merge --no-edit <+codebase.branch> || true
                      git push origin master
                      echo ""
                      echo "--- Step 3: Trigger Pages rebuild via API ---"
                      curl -s -X POST \
                        -H "Authorization: token <+secrets.getValue('github_pat')>" \
                        -H "Accept: application/vnd.github+json" \
                        "https://api.github.com/repos/hugefisco94/ai-orchestration-hub/pages/builds"
                      echo ""
                      echo "--- Step 4: Verify deployment ---"
                      sleep 30
                      STATUS=$(curl -s -H "Authorization: token <+secrets.getValue('github_pat')>" \
                        "https://api.github.com/repos/hugefisco94/ai-orchestration-hub/pages" \
                        | python3 -c "import json,sys; print(json.load(sys.stdin).get('status','unknown'))")
                      echo "Pages status: $STATUS"
                      test "$STATUS" = "built" && echo "✓ Deployment verified"
                      echo ""
                      echo "Target: https://hugefisco94.github.io/ai-orchestration-hub"
                      echo "✓ Harness Engineering deployment complete"
                    timeout: 10m
              - step:
                  name: Post-Deploy Health Check
                  identifier: health_check
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "=== Post-Deploy Health Check ==="
                      echo "Waiting for CDN propagation..."
                      sleep 15
                      HTTP_CODE=$(curl -sL -o /dev/null -w "%{http_code}" "https://hugefisco94.github.io/ai-orchestration-hub/" || echo "000")
                      echo "HTTP Status: $HTTP_CODE"
                      if [ "$HTTP_CODE" = "200" ]; then
                        echo "✓ Site is live and responding"
                      else
                        echo "⚠ Site returned $HTTP_CODE — CDN may still be propagating"
                        echo "Manual verification: https://hugefisco94.github.io/ai-orchestration-hub/"
                      fi
                    timeout: 5m
          failureStrategies:
            - onFailure:
                errors:
                  - AllErrors
                action:
                  type: ManualIntervention
                  spec:
                    timeout: 1h
                    onTimeout:
                      action:
                        type: Abort
